name: tests
on: [push]
jobs:
  test:
    name: PHP ${{ matrix.php-version }} unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
    steps:
      - uses: actions/checkout@v2
      - name: Cache composer downloads
        uses: actions/cache@v1
        with:
          path: /home/runner/.composer/cache/files
          key: composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-
      - uses: php-actions/composer@v1
      - name: Run phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage/coverage.xml
      - name: Upload code coverage artifact
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage/coverage.xml
  coverage:
    name: Publish code coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Download code coverage artifact
        uses: actions/download-artifact@v1
        with:
          name: coverage
      - name: Upload code coverage
        run: bash <(curl -s https://codecov.io/bash) -Z -t ${{ secrets.CODECOV_TOKEN }} -f coverage/coverage.xml